version: "3.7"
# Full details- https://github.com/localstack/localstack
services:
  localstack:
    image: localstack/localstack:latest #localstack/localstack:latest
    ports:
      - '4563-4599:4563-4599' # ports of the different services
      - '9000:9000'
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DEFAULT_REGION=eu-west-1 # This is the region where your localstack mocks to be running
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

#  localstack-full: # paid
#    image: localstack/localstack-full:latest
#    ports:
#      - '4563-4599:4563-4599' # ports of the different services
#      - '9000:9000'
#    environment:
#      - SERVICES=s3
#      - DEBUG=1
#      - DEFAULT_REGION=eu-west-1 # This is the region where your localstack mocks to be running
#      - PORT_WEB_UI=9000
#      - START_WEB=1
#    volumes:
#      - "/var/run/docker.sock:/var/run/docker.sock"
