# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      release:
        description: 'Release'
        required: false
        default: 'false'
      tags:
        description: 'Description'
jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            backend:
              - 'employee-service/**'

  # JOB to release frontend
  release:
    needs: changes
    if: ${{ needs.changes.outputs.backend == 'true' || github.event.inputs.release == 'true'}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.x
      - run: mvn -f employee-service/pom.xml clean install

      - name: Build Images using JIB
        run: mvn -f employee-service/pom.xml  -Dmaven.test.skip=true package jib:build -Djib.to.auth.username=${{ secrets.DOCKERHUB_USERNAME }} -Djib.to.auth.password=${{ secrets.DOCKERHUB_PASSWORD }}

